# Generated by Django 3.0.5 on 2020-04-22 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0004_auto_20200421_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinglog',
            name='idle_duration',
        ),
        migrations.RemoveField(
            model_name='trackinglog',
            name='idle_end_time',
        ),
        migrations.RemoveField(
            model_name='trackinglog',
            name='idle_start_time',
        ),
        migrations.CreateModel(
            name='IdleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking_app.TrackingLog')),
            ],
        ),
    ]
