# Generated by Django 2.2.8 on 2019-12-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='panel_min_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='panel_min_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='trending_max_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='trending_min_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='trending_min_likes',
            field=models.IntegerField(default=0),
        ),
    ]
