# Generated by Django 2.2.8 on 2019-12-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_app', '0002_auto_20191209_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='idea',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
