# Generated by Django 2.2.8 on 2019-12-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('ideas_app', '0003_auto_20191210_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
            preserve_default=False,
        ),
    ]
