# Generated by Django 2.2.8 on 2019-12-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_app', '0004_idea_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
