# Generated by Django 2.2.8 on 2020-01-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas_app', '0008_auto_20200114_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
