# Generated by Django 3.0.5 on 2020-04-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0002_trackinglog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinglog',
            name='sys_uptime',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
